### ISSUE TITLE
I'd love to see a conventional format for the "with" keyword

### ISSUE THREAD

**Issue by laserlemon** [christopheradams/elixir_style_guide#101]
I've seen:

``` elixir
with {:ok, user} <- User.get(id),
     {:ok, posts} <- Post.by_author(user)
do
  {:ok, posts}
else
  error -> error
end
```

``` elixir
with \
  {:ok, user} <- User.get(id),
  {:ok, posts} <- Post.by_author(user)
do
  {:ok, posts}
else
  error -> error
end
```

amongst others including using the `do:` form of the block, although I'm not sure if that format works with an `else` clause as well.

**Comment by laserlemon** [comment]
I love the second form if it weren't for that pesky backslash. For that reason, I lean toward the first version.

**Comment by bill-mybiz** [comment]
Howdy. You might find [this `with` syntax gist](https://gist.github.com/bill-mybiz/f0c771a97ba303214eafc83100706cc2) I did awhile back to try to get to a `with` convention that allows for (optional) comments before each step. I try to write self-documenting code where comments aren't necessary, but sometimes it is very useful to be able to do this. 

Because of this, the first version you have will have the comment before the entire `with` statement, which I dislike because it looks like you're commenting on the `with` statement as a whole as opposed to the first clause.

```
# 1. This comment is to the left and looks like it's for the `with` statement
with {:ok, user} <- User.get(id),
     # 2. This comment is to the right, etc. 
     {:ok, posts} <- Post.by_author(user)
do
  {:ok, posts}
else
  error -> error
end
```

So I [posted a suggested tweak on elixir forum](https://elixirforum.com/t/with-tweak-feature-request-first-clause-on-new-line/1671), wherein I was pointed to the `\` syntax. I thought that was great! ...only the `\` operator [doesn't allow for the immediately following line to be a comment](https://github.com/elixir-lang/elixir/issues/5246).

But thankfully there was another alternative mentioned that uses parentheses:

```
with(
  {:ok, user} <- User.get(id),
  {:ok, posts} <- Post.by_author(user)
) do
  {:ok, posts}
else
  error -> error
end
```

This has several benefits:
1. It allows for comments like I mentioned.
2. It is less asymmetrical than the `\` version
3. It always has the same indentation.
4. The indentation allows for the maximum usage of the width of the line.
5. The `do` block is cleanly and clearly separated from the preceding clauses and `else` clause.

This is now how I do all of my `with` statements. I thought you might like to hear about some of the reasoning behind the `\` version and consequences of it and the parentheses version.

**Comment by christopheradams** [comment]
@bill-mybiz from [this reply](https://elixirforum.com/t/with-tweak-feature-request-first-clause-on-new-line/1671/5) it seems the no comment after `/` is a bug in the compiler. Did you ever follow up on that?

**Comment by bill-mybiz** [comment]
@schnittchen Yes, at first I also liked the `\` version which is why I went with that when it was suggested. But I prefer the paren version now, because it not only allows for the comments, but also it cleans up and resolves the `do` issue - `, do:` vs `do...end`.

@christopheradams Deja [yep](https://github.com/elixir-lang/elixir/issues/5246). :smile:

**Comment by christopheradams** [comment]
OK, so not a bug then if I read that right @bill-mybiz. thanks for the link.

**Comment by bill-mybiz** [comment]
@christopheradams Yes, it was a great insight to compare the behavior against Ruby and bash. I'm really enjoying the decision making going on with Elixir core stuff!

**Comment by christopheradams** [comment]
This is the style presented [in the docs][with], although it may be hard to see since it's shown in an IEX session:

```elixir
# with just do (a)
with :ok <- :ok,
     :ok <- :ok,
  do: :ok

# with else (b)
with :ok <- :ok,
     :ok <- :ok do
  :ok
else
  :error ->
    :error
end
```

(This indentation style is supported by Emacs elixir-mode. What does everyone else's editor do with this?)

issue refs: [348][348], [349][349], [350][350]

[with]: https://hexdocs.pm/elixir/Kernel.SpecialForms.html#with/1
[348]: https://github.com/elixir-lang/emacs-elixir/pull/348
[349]: https://github.com/elixir-lang/emacs-elixir/issues/349
[350]: https://github.com/elixir-lang/emacs-elixir/pull/350

**Comment by christopheradams** [comment]
Here's my summary so far:

1) indenting each main `with` argument is the preferred style
2) `do` vs. `do:` depends on whether you have more than one line to do; if you have an `else` then use `do` (so maybe `do` should always be preferred?)
3) `do` on a line by itself or not? docs and emacs prefer not. some of you prefer yes. (no other style rules have `do` on a line by itself.)
4) if you must comment above each `with` argument, use parentheses

What to you think?

**Comment by christopheradams** [comment]
I opened PR #124 for this. I didn't add a rule about commenting above `with` clauses, since it's relatively complicated and uncommon. But if there were a rule it might read something like this (not sure how to describe with to do with `do`):

* If you need to add a comment above each `with` clause, surround them with
  parentheses. Put each clause on its own line, indented two spaces.

  ```elixir
  with(
    # look up foo
    {:ok, foo} <- fetch(opts, :foo),
    # look up bar
    {:ok, bar} <- fetch(opts, :bar)
  ) do
    {:ok, foo, bar}
  end
```

**Comment by bill-mybiz** [comment]
@christopheradams I think overall your changes look like they reflect the majority of core developers. :+1: 

I mainly pointed out the paren version to show the reasoning behind the `\` version, which I personally had mentioned both on the Elixir Forum and in the compiler issue I linked to (so perhaps I was responsible for their confusion). I tried to explain the dynamics of the paren version from my personal experience, because I use `with` _a lot_, i.e. almost every primary function. I used to do it the ways you are listing, but for me, they were insufficient. :no_entry: :wink: 

As an aside, I found your observation that no other rules have the `do` keyword on its own line very interesting. I'd say the reason that the `do` keyword is on the same line in other rules is that the bulk of code is usually _inside_ the `do` block. The `with` construct is the only one that has the _arguments_ be the bulk of the code with the `do` block being most commonly a simple return value.

**Comment by christopheradams** [comment]
An alternative indentation for `do:` is shown in [this rule from a different guide](https://github.com/lexmag/elixir-style-guide/blob/master/README.md#with-indentation):

```elixir
with {:ok, date} <- Calendar.ISO.date(year, month, day),
     {:ok, time} <- Time.new(hour, minute, second, microsecond),
     do: new(date, time)
```

If that style catches on we can consider it.
