### ISSUE TITLE
Multiline pipeline syntax

### ISSUE THREAD

**Issue by syamilmj** [christopheradams/elixir_style_guide#103]
Consider the codes below:

```
File.stream!("path/to/some/file", read_ahead: 100_000) # NEW!
|> Flow.from_enumerable()
|> Flow.flat_map(fn line ->
    for word <- String.split(empty_space), do: {word, 1}
   end)
|> Flow.partition_with(storage: :ets) # NEW!
|> Flow.reduce_by_key(& &1 + &2)
|> Enum.to_list()
```

Notice the pattern in this bit:

```
Flow.flat_map(fn line ->
  for word <- String.split(empty_space), do: {word, 1}
end)
```

`for` is only indented by two spaces, and `end)` is indented on the line as `Flow`

I have seen many different ways on how they were written, but this seems to be cleanest way.

Ref: http://elixir-lang.org/blog/2016/07/14/announcing-genstage/

**Comment by christopheradams** [comment]
In your pipes example and the one you link to `for` is only indented by one space instead of two. Does that seem odd to anyone else?

**Comment by asaaki** [comment]
The pipe operator is not the nicest player when it comes to indentation based on factor 2, since it leads to 3 spaces in front of the statements.

```
123↓
|> Foobar
   not working, if "aligned" to above statement
   (3 spaces vs. 2 or 4 spaces)
|> sorry
```

```
123↓
|> Foobar
    not working, because we are off by 1 to above
    and are actually introducing 4 space intendation
|> sorry
```

How do I avoid such mess? In multiline pipes with multiline functions I always extract the functions, because they already distract the visual flow for the pipeline.

So personally I don't even care so much, if there was a guideline for multiline pipelines with necessary indentation, because I have the feeling that such pattern is already a bad one (like a code smell). But again, this is just my opinion.

**Comment by christopheradams** [comment]
Multiline pipeline syntax should now look like:

```elixir
    File.stream!("path/to/some/file", read_ahead: 100_000)
    |> test()
    |> test(fn line ->
      for word <- String.split(" "), do: {word, 1}
    end)
```
