### ISSUE TITLE
Keyword Wrapping (`[]` Brackets)

### ISSUE THREAD

**Issue by DavidAntaramian** [christopheradams/elixir_style_guide#118]
As discussed in #113, there is no guidance regarding when keywords should be wrapped in square brackets and when they shouldn't be.

With regards to `defstruct`, it seems that the same source material referred to in #113 establishes a precedent that keywords used in `defstruct` declarations should not be wrapped in square brackets. The referenced sources:

  - [Elixir](https://github.com/elixir-lang/elixir/blob/f1cc31be3cecad911f05a536be91857702c2b766/lib/elixir/lib/uri.ex#L10)
  - [Ecto](https://github.com/elixir-ecto/ecto/blob/8f1b5222a760c824340e38a66dd935686c66eaf4/lib/ecto/log_entry.ex#L29)
  - [Phoenix](https://github.com/phoenixframework/phoenix/blob/297f81c7154149a13f9b61f069f5cc1b43816f3d/lib/phoenix/socket.ex#L139)

**Comment by corroded** [comment]
@DavidAntaramian This has been merged, can we close this? :)

**Comment by corroded** [comment]
So should the rule be:

- `defstruct` keyword lists spanning multiple lines should be aligned like the examples given AND should have no square brackets?

**Comment by christopheradams** [comment]
I did a quick survey of some of the top packages, and there's about a 50/50 split between brackets and no brackets for `defstruct` arguments.

However, for the most part the brackets only show up where they are required: when atoms are used for `nil` defaults, like `[:username, admin: false]` instead of `[username: nil, admin: false]`. It might be helpful to point out this exception?

**Comment by christopheradams** [comment]
@DavidAntaramian @corroded Please check out #145.
