### ISSUE TITLE
comment annotation examples

### ISSUE THREAD

**Issue by nhooyr** [christopheradams/elixir_style_guide#133]
There are no examples for https://github.com/christopheradams/elixir_style_guide#comment-annotations

We should have some to make everything crystal clear.

**Comment by christopheradams** [comment]
Which comment annotations are most in need of examples?

**Comment by nhooyr** [comment]
An example for the third point would be nice. https://github.com/christopheradams/elixir_style_guide#multiple-line-annotations

It would automatically cover the previous two.

something like

```elixir
# TODO: Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nam nunc ex, fringilla
#  rhoncus arcu sed, venenatis luctus mi.
def some_func do
end
```

And for point 4, should a colon still be included or just `#ANNOTATION`?

**Comment by christopheradams** [comment]
Are any big Elixir libraries even following this rule? This might be a good opportunity to review this section.

**Comment by christopheradams** [comment]
> And for point 4, should a colon still be included or just #ANNOTATION?

Yes, a colon should be used after the comment ANNOTATION. This is the preferred style. It should also be uppercase, which is not currently mentioned.

The [multiple-line-annotations] rule (two-space indent for subsequent comment lines) is not followed in the Elixir community as far as I can tell, so that rule can be dropped.

[multiple-line-annotations]: https://github.com/christopheradams/elixir_style_guide#multiple-line-annotations

**Comment by christopheradams** [comment]
@nhooyr Please check PR #134, and let me know if the comment examples are sufficient, or if you think we should add anything.
