### ISSUE TITLE
Function return pattern

### ISSUE THREAD

**Issue by CatTail** [christopheradams/elixir_style_guide#154]
I'm new to Elixir/Erlang, but I think there is an common return pattern for error handling,

```elixir
def dosomething do
  if process_ok() do
    {:ok, extra_data}
  else
    {:error, err}
  end
end
```

Am I correct, and this should be part of this style guide?

**Comment by christopheradams** [comment]
@CatTail you are right that return tuples with `:ok` and `:error` are very common in Erlang/Elixir and come highly recommended. See for example [Error Handling in Elixir Libraries](http://michal.muskala.eu/2017/02/10/error-handling-in-elixir-libraries.html).

I'm not convinced that a rule about this should be included in this guide, since it pertains to API design rather than style/formatting.

I will say that a clearer rule that could introduce this concept is the recommendation that for any pair of functions, where the first returns error values (e.g, `:ok | {:error, reason}`, `{:ok, value} | :error}`, etc), and the second raises an exception, should be named `some_func()` and `some_func!()`, respectively. That is clearly a style guideline that has no bearing on functionality.

**Comment by CatTail** [comment]
Thanks @christopheradams , I'm going to close this issue.
