### ISSUE TITLE
Placement of defguard?

### ISSUE THREAD

**Issue by fireproofsocks** [christopheradams/elixir_style_guide#191]
Thanks for the thorough guide!

Is there a comment somewhere that would advise where to put `defguard`?

**Comment by christopheradams** [comment]
I would recommend putting any `defguard` right above the regular `def` functions, but after all of the module attributes, import directives, types, `defstruct`, etc.

Here's an example from the [Integer](https://github.com/elixir-lang/elixir/blob/v1.10.3/lib/elixir/lib/integer.ex#L1) module.

Also, because "Guards" are listed before "Functions" in [the documentation](https://hexdocs.pm/elixir/Integer.html#summary), this feels like a natural placement order.

Should we add this to our Modules section?
