### ISSUE TITLE
using pipe with only 2 functions

### ISSUE THREAD

**Issue by sescobb27** [christopheradams/elixir_style_guide#193]
what should be used in this case

```elixir
MyMod.my_fun() |> MyMod2.my_fun2()
```

or 

```elixir
MyMod2.my_fun2(MyMod.my_fun())
```

**Comment by christopheradams** [comment]
The rule to [avoid single pipelines] still applies in this case, so that would prefer:

```elixir
MyMod2.my_fun2(MyMod.my_fun())
```

There are numerous examples of this preferred style in the core libraries. For example, from the `Mix.Local` module:

```elixir
{:ok, current_version} = Version.parse(System.version())
```

In real-world usage, I'm not convinced that lack of a pipe operator in this case makes the code less readable. 

[avoid single pipelines]: https://github.com/christopheradams/elixir_style_guide#avoid-single-pipelines
