### ISSUE TITLE
Pipeline with single pipe operator for common cases like Enum.map/reduce/filter

### ISSUE THREAD

**Issue by alexDevBR** [christopheradams/elixir_style_guide#194]
I'm not sure about this one:
- Avoid using the pipe operator just once.

I agree with the example `String.downcase(some_string)`
But what about pipelines with Enum.map/filter/reduce? Wouldn't it be more consistent to always use a pipe?
Which one would is more readable:

```elixir
a = some_enum  |> Enum.map(fn x -> ... end)
b = other_enum |> Enum.filter(fn x -> ... end) |> Enum.map(fn x -> ... end)
```
or

```elixir
a = Enum.map(some_enum, fn x -> ... end)
b = other_enum |> Enum.filter(fn x -> ... end) |> Enum.map(fn x -> ... end)
```
?

**Comment by christopheradams** [comment]
It's not unknown to use a bare variable with a single pipe into an `Enum`. For example, here's a line from [Credo]:

```elixir
filenames = nodes |> Enum.map(&(&1.filename))
```

[Credo]: https://github.com/rrrene/credo/blob/80b9a2efdb872157317de4b126e54441f3551f18/lib/credo/check/refactor/nesting.ex#L11

Here's another example from [Coverex]:

```elixir
mc = mods |> Enum.map(fn(mod) -> {mod, cover_per_mod(mod)} end)
```

[Coverex]: https://github.com/alfert/coverex/blob/master/lib/coverex/source.ex#L35

I understand the argument for readability here, however it's rare to format it this way. In fact, I couldn't find any examples from the standard library or top packages. Most code avoids single pipes, even with `Enum`, which is why we state it as the preference.

**Comment by alexDevBR** [comment]
Hi cristopher, thanks for the opinion! After posting this I found [this issue in credo](https://github.com/rrrene/credo/issues/221) where they discuss having a check for this. In the end they implemented it, but It seems they themselves aren't using it!

There are is another good argument favoring single pipes there: a single pipe might eventually become a longer pipe and to refactor it is just added work. I think this applies especially in this case because it's very common to add constraints, transformations to an Enum pipeline. In the case of Enum I see it as a short pipeline, not as a function call. But I might be biased, since I come from an OO background, that's why I wanted to hear what the community has to say!

**Comment by christopheradams** [comment]
Credo does have a check to warn for single pipe use, but I think it's disabled by default. Still, the core team and most package maintainers avoid them, so we'll keep "no single pipes" as the preference for now. Thanks!
