### ISSUE TITLE
Nested defmodule

### ISSUE THREAD

**Issue by Odaeus** [christopheradams/elixir_style_guide#196]
Hi,

The [module attribute ordering](https://github.com/christopheradams/elixir_style_guide#module-attribute-ordering) seems to be missing a recommendation on where `defmodule` should go for nesting modules. Such as when you want a struct that doesn't need its own file.

I'd suggest after `defstruct`?

**Comment by christopheradams** [comment]
Nested modules are not that common, so it's hard to say if there's an accepted style. In general, they would be well-placed after any `defstruct` and any `@type` definitions, but before the parent module's functions.

Here's an example from the standard library: https://github.com/elixir-lang/elixir/blob/9b6ec7bae79ececfb9ed481c780febb6a5b293e8/lib/elixir/lib/version.ex#L109

**Comment by Odaeus** [comment]
Sounds fine to me!

I use it a lot for structs but I notice a project like HTTPoison defines them in the [same file but outside of the module](https://github.com/edgurgel/httpoison/blob/a31aa4d91b73013a54960cfa85ae839547b01066/lib/httpoison.ex#L56). Do you think that style is more common? I assume not so much that it should be recommended in the style guide instead of nesting.

Please let me know if I should submit a PR with the nested `defmodule` addition.

**Comment by christopheradams** [comment]
This guide has already settled on a preference [for one module per file](https://github.com/christopheradams/elixir_style_guide#one-module-per-file), which would suggest nesting modules rather than defining them one after the other as HTTPoison does.

It's hard to recommend a precise location for nested `defmodule` since there aren't many examples to go on. We can agree it should go after `defstruct` but before any functions. If forced to choose, I would include it in item **xiii**, as "`defmacro`, `defmodule`, `defguard`, `def`, etc." and place `defmodule` after `defmacro`, since everything above that seems more like the module's preamble, and everything after that the real working code.

What do you think?

**Comment by Odaeus** [comment]
Sounds reasonable 👍

**Comment by christopheradams** [comment]
A PR would be welcome on this!
