### ISSUE TITLE
An another style guide to borrow some points from

### ISSUE THREAD

**Issue by lexmag** [christopheradams/elixir_style_guide#59]
I've recently released [an another Elixir style guide](https://github.com/lexmag/elixir-style-guide).
It will continue to grow intensively.
I hope that you can borrow many points from it, which don't present here.

\cc @eksperimental

**Comment by whatyouhide** [comment]
I generally don't like the idea of two style guides because I feel it may defeat the purpose of having a style guide. Should we just focus all our efforts in either this one or @lexmag's one? (btw @lexmag, great work :+1: :) )

**Comment by alxndr** [comment]
To throw more fuel on the fire, there's also [the style checker Dogma](https://github.com/lpil/dogma) with [its own set of rules](https://github.com/lpil/dogma/tree/214b14a8987a3fab35776de359da8c8e6dc9987f/lib/dogma/rule).

**Comment by lexmag** [comment]
Hey @whatyouhide, I don't really think of my guide as of the community-driven (at least for now), it's purely opinionated.
It states a style I developed working with Elixir during last 2 years, it works for my colleagues and friends of mine.
I'd be happy if it works for everyone without any adjustment, but it may have some rules which don't appeal to everyone, though I consider them practical and pragmatic, e.g. https://github.com/lexmag/elixir-style-guide#zero-arity-parens.
Thus I just think current guide can benefit from mine – borrow and adjust some points (if it's needed).

**Comment by eksperimental** [comment]
@lexmag thanks for the heads-up, and congratulations for the good job.
Actually you have done it, but i wanted to contribute to this guide based on the latest changes done prior to the release of Elixir v1.1 that were done cleaning up code, but i think you pretty much got everything in your guide.
I have read it, and will re-read it and contribute to it, as I am keeping track of all the changes I made to cleanup code in elixir, and also contribute them to this guide.

Regarding having more than one style-guide, I think we can benefit much more by having different sources to take ideas from (provided that licenses are compatible), specially as @lexmag said, when a lot of those choice could be just considered personal taste.

**Comment by eksperimental** [comment]
Same as we have a section for tools, I think we should have a section for **Other Style guides**
and include this one and other relavant ones that people might create in the future.
as they can help people to expand their own ideas (and also contribute to this guide)

**Comment by niftyn8** [comment]
My 2 cents...

The truth of the matter is there are really good arguments for *most* intentional stylistic decisions. The only real purpose of a style guide is as documentation of which decisions have been made to try to keep a group of people in line with those decisions.

I have *very* little patience for most of the stylistic arguments that happen myself. I have some preferences of my own but I tend to just follow whatever other people are doing on a project I'm working on.

Every job I've been at has held everyone to a different style guide even when I've used the same language at different jobs. We have our own private style guide at my current job for Javascript, for example. As another example, look at just how many [open source Ruby style guides](https://github.com/search?utf8=%E2%9C%93&q=ruby-style-guide) exist on Github.

It's totally natural for people to disagree with points in a particular style guide and roll their own for their own team's purposes. Totally fine.

As @lexmag has said above, his style guide is not intended to be community driven but opinionated according to its maintainers (at the moment, @lexmag and one other Github user).

This style guide is meant to be community driven. I almost don't contribute at all besides paying attention to PRs and trying to stay ready to diffuse situations if they occur (they haven't yet *phew*) . I only support it as a good place to point Elixir beginners because A) It happens to be in the Dave Thomas book last time I checked and B) It's gotten a lot of stars and contributors :confetti_ball:. If another repo surpasses it, :fireworks:.

Feel free to pull ideas from @lexmag's guide and open PRs to this repo if you think they should be included.

Feel free to add an *Other Style Guides* section if you think that's a good choice. 

¯\\_(ツ)_/¯
